se hicieron los cambios pedidos en git
jmtov/yosoy-htg pull request #2
Opened 2020-03-25 18:55 UTC by luisrodolfoduarte

#Descripción

Se hicieron los cambios solicitados como espaciados, identeación y acoplar componentes a uno.
También se agregó Media Query.

#Adjunto imágenes
![Captura de pantalla de 2020-03-25 15-53-55](https://user-images.githubusercontent.com/19716528/77574597-06c40d80-6eb1-11ea-8abe-7164b89d8741.png)
![Captura de pantalla de 2020-03-25 15-54-02](https://user-images.githubusercontent.com/19716528/77574601-088dd100-6eb1-11ea-8277-b9e72973e48d.png)
![Captura de pantalla de 2020-03-25 15-54-10](https://user-images.githubusercontent.com/19716528/77574602-09266780-6eb1-11ea-8924-d73ee669949d.png)

2020-03-27 15:29 UTC, jmtov requested changes
¡Buen trabajo, Rodo! 👌 

Recuerda que si se solicitaron cambios en el PR, no se debería hacer el merge hasta que esos cambios sean aprobados.

Por otro lado, te recuerdo revisar el [documento de estandarización de código](https://docs.google.com/document/d/1gJ0gB1NkinQXyRe5dk71yMUYE8c6dupLc-lYQ0osSro/edit#) para que tengas en cuenta por qué es importante mantener el código organizado.

También, recuerda poner imágenes de las funcionalidades desarrolladas (la vista en la página), mas no del código, pues al final, el código se puede ver en el tab de "Files Changed" 😉

2020-03-27 15:29 UTC, jmtov commented on src/components/Home/index.js
> +            </div>
Presta atención al indentado. Recuerda pasarte por la [guía de estandarización de código](https://docs.google.com/document/d/1gJ0gB1NkinQXyRe5dk71yMUYE8c6dupLc-lYQ0osSro) para ver cómo hacerlo.
```suggestion
                <div className={styles.containerButton}>
                    <button className={styles.button1}>QUIERO DONAR</button>
                    <button className={styles.button2}>QUIERO PEDIR</button>
                </div>
            </div>
```

2020-03-27 15:29 UTC, jmtov commented on src/components/Home/styles.module.scss
> +    width:100%;
Presta atención al espaciado entre propiedades y valores. En la [guía](https://docs.google.com/document/d/1gJ0gB1NkinQXyRe5dk71yMUYE8c6dupLc-lYQ0osSro) vas a encontrar más información sobre por qué es importante. 
```suggestion
    width:100%;
```

2020-03-27 15:29 UTC, jmtov commented on src/components/Home/styles.module.scss
> +        transform: translateY(-5px);
Es mejor poner espaciados cuando hacemos nesting en SASS para que el código sea más legible.
```suggestion
    transition: all 1.2s;

    &:hover {
        transform: translateY(-5px);
```
También revisaría un poco la duración de la transición, quizá para ser la transición de hover de un botón, sea muy lenta. Te dejo un [artículo](https://material.io/design/motion/speed.html#) donde explica un poco cómo manejar animaciones y transiciones de acuerdo a la manera en que lx usuarix está interactuando con los elementos.

2020-03-27 15:29 UTC, jmtov commented on src/components/Home/styles.module.scss
> +        cursor:pointer;
Atención a los espaciados.

2020-03-27 15:29 UTC, jmtov commented on src/components/Home/styles.module.scss
> +        transform: translateY(-5px);
Ten en cuenta el comentario de arriba respecto a los espaciados y a la duración de las transiciones.

```suggestion
    transition: all 1.2s;

    &:hover {
        transform: translateY(-5px);
```

2020-03-27 15:29 UTC, jmtov commented on src/components/Home/styles.module.scss
> +    }
Procura que la indentación sea consistente en todo el archivo y tenga en cuenta los niveles de jerarquía:
```suggestion
    .containerButton, .containerHome {
        width: 100%;
    }
```

2020-03-27 15:29 UTC, jmtov commented on src/components/Home/styles.module.scss
> +  }
Recuerda dejar una línea vacía al final de cada archivo. Puedes leer más acerca del porqué en [éste artículo](https://thoughtbot.com/blog/no-newline-at-end-of-file).

2020-03-27 23:58 UTC, leoromero97 commented on src/components/Home/styles.module.scss
> +        transform: translateY(-5px);
Gracias Kike por el articulo, muy bueno !

2020-03-28 00:00 UTC, leoromero97 commented on src/components/Home/index.js
> +            </div>
Instale el EsList, y lo revise, se supone que ahora esta corregido

2020-03-30 20:50 UTC, jmtov approved these changes
¡Muy bien!

2020-03-30 20:50 UTC, jmtov commented on src/components/vistas/home/index.js
> +                    <div className={styles.containerHome}>
Creo que podrían usar sólo un `div`, ¿no?

2020-03-30 20:50 UTC, jmtov commented on src/components/vistas/home/index.js
> +                            {}
👀  ¿Y esto?

2020-03-30 20:50 UTC, jmtov commented on src/components/vistas/home/index.js
> +                    <div className={styles.containerButton}>
También, creo que acá podrían dejar sólo uno de los `div`s y unir los estilos.

2020-03-30 20:50 UTC, jmtov commented on src/components/vistas/home/styles.module.scss
> +    display: block;
Espacios:
```suggestion
}

.hr {
    display: block;
```

2020-03-30 20:50 UTC, jmtov commented on src/components/vistas/home/styles.module.scss
> +    &:hover {
Espacios:
```suggestion
    transition: all 1.2s;

    &:hover {
```

2020-03-30 20:50 UTC, jmtov commented on src/components/vistas/home/styles.module.scss
> +    &:hover {
Espacios:
```suggestion
    transition: all 1.2s;

    &:hover {
```

2020-03-30 20:50 UTC, jmtov commented on src/components/vistas/home/styles.module.scss
> +
Este espacio sobra.

2020-03-30 20:50 UTC, jmtov commented on src/components/vistas/home/styles.module.scss
> +            width: 100%;
Indentación:
```suggestion
        width: 100%;
```

2020-03-30 20:50 UTC, jmtov commented on src/components/vistas/home/styles.module.scss
> +    .containerButton {
Espacios:
```suggestion
    }

    .containerButton {
```

2020-03-30 20:50 UTC, jmtov commented on src/components/vistas/home/index.js
> +              {}
Reemplaza esto por un comentario que diga para lo que se usará. Ejemplo: 
```suggestion
              {/* TODO: Aquí va el componente que ... */}
              {}
```

2020-03-30 20:56 UTC, merged