Slide2
jmtov/yosoy-htg pull request #3
Opened 2020-03-25 22:12 UTC by luisrodolfoduarte

#Descripcion

Se maqueto la segunda vista, seleccion de medicamentos. Esperamos aprobacion para mergear.

Adjunto imagenes principales:
![Captura de pantalla de 2020-03-25 19-10-42](https://user-images.githubusercontent.com/19716528/77590434-75629480-6ecc-11ea-9218-a2a465b51402.png)
![Captura de pantalla de 2020-03-25 19-11-09](https://user-images.githubusercontent.com/19716528/77590435-772c5800-6ecc-11ea-9728-89b644f08b5f.png)
![Captura de pantalla de 2020-03-25 19-11-14](https://user-images.githubusercontent.com/19716528/77590437-77c4ee80-6ecc-11ea-965e-972d66b93085.png)
![Captura de pantalla de 2020-03-25 19-11-19](https://user-images.githubusercontent.com/19716528/77590439-78f61b80-6ecc-11ea-9fda-fb7840c9ef6d.png)

2020-03-27 15:56 UTC, jmtov requested changes
¡Buen trabajo con la vista!

En general te diría que prestaras atención a:
- Los espaciados entre instrucciones ❌`return();` 👌 ` return ();`
- Las líneas vacías al final de los archivos.
- Los espaciados entre propiedades e instrucciones en SASS.
- Las duraciones de las transiciones en los botones.

También, me parece que copiaste los archivos del componente de tarjeta en dos partes:

`src/components/contenedor-medicamentos/tarjetas/contSuperior/index.js`
`src/components/contenedor-medicamentos/contPastis/tarjetas/contSuperiocor/index.js`

Revisa cuál es el correcto y elimina el otro para no generar confusión.

2020-03-27 15:56 UTC, jmtov commented on src/components/Assets/index.js
> +import logo from "./logo.png"
Procura mantener la consistencia en el estilo de código.
```suggestion
import logo from "./logo.png";
```

2020-03-27 15:56 UTC, jmtov commented on src/components/button/index.js
> +class Button extends React.Component{
Ya que no hay mucha lógica en este componente, te recomendaría volverlo una función (en vez de una clase), con esto mejoraría el performance general de la aplicación.

2020-03-27 15:56 UTC, jmtov commented on src/components/button/index.js
> +        return(
Presta atención a los espaciados entre las instrucciones para que el código sea más legible.
```suggestion
        return (
```

2020-03-27 15:56 UTC, jmtov commented on src/components/button/index.js
> +export default Button;
Recuerda la línea vacía al final del archivo.

2020-03-27 15:56 UTC, jmtov commented on src/components/button/style.module.scss
> +        transform: translateY(-5px);
Recuerda los espaciados entre propiedades y declaraciones de SASS. También ten en cuenta el comentario hecho en [PRs  anteriores](https://github.com/jmtov/yosoy-htg/pull/2#pullrequestreview-382954647) respecto a la duración de las transiciones.

2020-03-27 15:56 UTC, jmtov commented on src/components/contenedor-medicamentos/contPastis/index.js
> +class ContPastis extends React.Component{
Ya que no hay mucha lógica en este componente, convendría volverlo una función.

2020-03-27 15:56 UTC, jmtov commented on src/components/contenedor-medicamentos/contPastis/index.js
> +        return(
Atención a los espacios entre instrucciones.
```suggestion
    render() {
        return (

```

2020-03-27 15:56 UTC, jmtov commented on src/components/contenedor-medicamentos/contPastis/index.js
> +export default ContPastis;
Recuerda la línea vacía al final del archivo.

2020-03-27 15:56 UTC, jmtov commented on src/components/contenedor-medicamentos/contPastis/style.module.scss
> +}
Recuerda la línea vacía al final del archivo.

2020-03-27 15:56 UTC, jmtov commented on src/components/contenedor-medicamentos/contPastis/style.module.scss
> +.contPastis{
Presta atención a los espacios entre instrucciones.

2020-03-27 15:56 UTC, jmtov commented on src/components/contenedor-medicamentos/contPastis/tarjetas/contInferior/index.js
> +class ContInferior extends React.Component{
Mismo comentario respecto a la lógica del componente. Como es un componente simple, puede ser una función.

2020-03-27 15:56 UTC, jmtov commented on src/components/contenedor-medicamentos/contPastis/tarjetas/index.js
> +                <ContInferior/>
Ya que los componentes `ContSuperior` y `ContInferior` solo se usan para pintar información, sería mejor que sus contenidos se escribieran directamente acá. Si bien dividir en componentes está bien, dividir mucho puede hacer que el código sea difícil de entender.

2020-03-27 15:56 UTC, jmtov commented on src/components/contenedor-medicamentos/index.js
> +    }
El componente en `src/components/contenedor-medicamentos/contPastis/index.js` tiene casi lo mismo. ¿Es el mismo componente?

2020-03-27 15:56 UTC, jmtov commented on src/components/contenedor-medicamentos/index.js
> +export default ContainerPastis;
Atención a la línea vacía al final del archivo.

2020-03-27 15:56 UTC, jmtov commented on src/components/Assets/index.js
> +];
Recomendaría que esto fuese un objeto. Con eso, cuando se llame desde el topbar, sería más fácil saber qué ícono hace referencia a qué key.

2020-03-27 15:56 UTC, jmtov commented on src/components/topbar/index.js
> +            <Back assets={imgNavbar[0]}/>
Acá no sería necesario crear un componente para `Back` y un componente para `Logo` ya que sólo se están usando para pintar un elemento de imágenes.

2020-03-27 15:56 UTC, jmtov commented on src/medicine-selector/index.js
> +    </div>
Procura no poner espacios de más.
```suggestion
      <div>
        <Topbar/>
         <div className={styles.contenedorPrincipal}>
          <Searcher contBuscador="¿Que medicamentos estas buscando?" title="MEDICAMENTOS UTILIZADOS"/>
          <ContainerPastis/>
          <Button title="Continuar"/>
        </div>
    </div>

```

2020-03-30 22:52 UTC, leoromero97 commented on src/components/button/index.js
> +class Button extends React.Component{
Ok, listo !

2020-03-30 22:56 UTC, leoromero97 commented on src/components/contenedor-medicamentos/contPastis/index.js
> +class ContPastis extends React.Component{
Ok, resuelto !

2020-03-30 22:56 UTC, leoromero97 commented on src/components/contenedor-medicamentos/contPastis/style.module.scss
> +}
Listo

2020-03-30 22:56 UTC, leoromero97 commented on src/components/contenedor-medicamentos/contPastis/style.module.scss
> +.contPastis{
listoo

2020-03-30 22:59 UTC, leoromero97 commented on src/components/contenedor-medicamentos/contPastis/tarjetas/contInferior/index.js
> +class ContInferior extends React.Component{
listo

2020-03-30 23:01 UTC, leoromero97 commented on src/components/topbar/index.js
> +            <Back assets={imgNavbar[0]}/>
El componente back, regresaria hacia atras! creo que deberia ir asi por el tema 'ciclos de vida'

2020-03-31 04:06 UTC, leoromero97 commented on src/components/Assets/index.js
> +];
Resuelto !

2020-03-31 04:15 UTC, leoromero97 commented on src/components/contenedor-medicamentos/contPastis/tarjetas/index.js
> +                <ContInferior/>
Resuelto !

2020-03-31 04:20 UTC, leoromero97 commented on src/components/contenedor-medicamentos/index.js
> +    }
Si, muestra las tarjetas con la informacion del medicamento o pastilla, pero para el maquetado principal lo hicimos asi. Despues lo vamos a mejorar y optimizar. Ya que muestra el mismo componente varias veces

2020-04-01 13:11 UTC, jmtov requested changes

2020-04-01 13:11 UTC, jmtov commented on src/components/medicine-container/targets/index.js
> +          </div>
¿No podría dejarse solo el `h1`? Intenta que el código siempre quede lo más sencillo posible.

2020-04-01 13:11 UTC, jmtov commented on src/components/medicine-container/targets/index.js
> +        </div>
Lo mismo acá.

2020-04-01 13:11 UTC, jmtov commented on src/components/medicine-container/targets/styles.module.scss
> +    border: solid pink 2px;
Me parece que este borde rosa no hace parte del diseño.

2020-04-01 13:11 UTC, jmtov commented on src/components/medicine-container/targets/styles.module.scss
> +    border: solid green 2px;
Tampoco este margen verde.

2020-04-01 13:11 UTC, jmtov commented on src/components/reusable-components/button/index.js
> +class Button extends React.Component {
¡Bien ahí con este componente!

2020-04-01 13:11 UTC, jmtov commented on src/components/reusable-components/searcher/form/styles.module.scss
> +  margin-top: -10px;
¿Porqué esta margen negativa? Quizá convenga revisar primero el padding del padre antes de entrar a poner una márgen negativa.

2020-04-01 13:11 UTC, jmtov commented on src/components/reusable-components/searcher/form/styles.module.scss
> +  background-color: rgb(216, 210, 210);
Veo que este color se repite en varios lugares. Convendría moverlo a una variable de SCSS.

2020-04-01 13:11 UTC, jmtov commented on src/components/reusable-components/button/styles.module.scss
> +  border-color: blue;
Revisaría que los colores sean los que están en el diseño.

2020-04-01 13:11 UTC, jmtov commented on src/components/reusable-components/button/styles.module.scss
> +  background-color: blue;
Lo mismo acá.

2020-04-01 13:11 UTC, jmtov commented on src/components/reusable-components/button/styles.module.scss
> +    box-shadow: 0 30px 30px #94dbf8;
Y acá.

2020-04-01 13:11 UTC, jmtov commented on src/components/reusable-components/topbar/back/index.js
> +}
Creo que ya había hecho un comentario respecto a este botón y al elemento de logo pero lo vuelvo a hacer: Como en realidad no tienen mucha lógica, no veo necesario el que estén separados en componentes. Quizá convenga tenerlos dentro de contenedores separados dentro del mismo componente de Topbar.

2020-04-01 13:11 UTC, jmtov commented on src/components/reusable-components/topbar/back/styles.module.scss
> +  background-color: blue;
Revisaría el azul que se usa acá para que sea igual que el color de los diseños.

2020-04-01 13:11 UTC, jmtov commented on src/components/reusable-components/searcher/form/index.js
> +        <input type="text" placeholder={this.props.contBuscador} className={styles.buscador} />
Si `this.props.contBuscador` es un placeholder, sería apropiado que esa prop se llame igual ya que haría más fácil entender para qué sirve.
```suggestion
        <input type="text" placeholder={this.props.placeholder} className={styles.buscador} />
```

2020-04-01 13:11 UTC, jmtov commented on src/components/vistas/medicine-selector/index.js
> +        <Searcher contBuscador="¿Que medicamentos estas buscando?" title="MEDICAMENTOS UTILIZADOS" />
Quizá el título vaya mejor estando en el contenedor de pastillas, ya que el título en sí hace referencia al listado y no a la barra de búsqueda.

2020-04-01 17:19 UTC, leoromero97 commented on src/components/vistas/medicine-selector/index.js
> +        <Searcher contBuscador="¿Que medicamentos estas buscando?" title="MEDICAMENTOS UTILIZADOS" />
listo !

2020-04-01 17:45 UTC, leoromero97 commented on src/components/reusable-components/topbar/back/styles.module.scss
> +  background-color: blue;
listo, igual creo que el color del boton esta desactivado por eso se ve en ese tono en el diseño, quedara para despues de la demo cuando implementemos funcionalidades

2020-04-01 18:04 UTC, leoromero97 commented on src/components/reusable-components/topbar/back/index.js
> +}
Ok, resuelto ! este va a ser la base de las otras topbar's

2020-04-01 19:23 UTC, jmtov requested changes
¡Muy bien con esos cambios!

2020-04-01 19:23 UTC, jmtov commented on src/components/medicine-container/styles.module.scss
> +h4 {
Recuerda el espaciado entre definiciones. También procura usar una clase para aplicar los estilos del título en vez del `h4`.

2020-04-01 19:23 UTC, jmtov commented on src/components/medicine-container/targets/index.js
> +            <img className={styles.imgPastilla} src={atripla} alt="medicineImagen" />
Ten cuidado con la indentación.

2020-04-01 19:23 UTC, jmtov commented on src/components/medicine-container/targets/index.js
> +class Targets extends React.Component {
Como recomendación, tarjeta se dice `Card` en inglés.

2020-04-01 19:23 UTC, jmtov commented on src/components/vistas/home/index.js
> +            {MedicineSelector}
Procura usar la notación JSX cuando se pueda.
```suggestion
            <MedicineSelector />
```

2020-04-01 19:30 UTC, leoromero97 commented on src/components/medicine-container/styles.module.scss
> +h4 {
listo !

2020-04-01 19:30 UTC, leoromero97 commented on src/components/medicine-container/targets/index.js
> +            <img className={styles.imgPastilla} src={atripla} alt="medicineImagen" />
listo !

2020-04-01 19:32 UTC, leoromero97 commented on src/components/vistas/home/index.js
> +            {MedicineSelector}
Estoy importando el componente siguiente, si uso la notacion ' <MedicineSelector /> se me pinta abajo !

2020-04-01 19:36 UTC, leoromero97 commented on src/components/medicine-container/targets/index.js
> +class Targets extends React.Component {
listo !

2020-04-01 19:52 UTC, jmtov approved these changes

2020-04-01 20:00 UTC, merged