realice la vista de fundaciones
jmtov/yosoy-htg pull request #4
Opened 2020-03-25 22:17 UTC by luisrodolfoduarte

#Descrpcion

Se maqueto la vista de seleccion de organizacion/fundacion.
Esperamos aprobacion para continuar

Aclaramos que hay cosas que veriamos mejor si se unen.

Adjunto vistas principales
![Captura de pantalla de 2020-03-25 19-17-16](https://user-images.githubusercontent.com/19716528/77590787-53b5dd00-6ecd-11ea-9906-8c373b88ac4b.png)
![Uploading Captura de pantalla de 2020-03-25 19-17-20.png…]()

2020-04-01 21:14 UTC, jmtov requested changes
¡Buen trabajo!

Te dejé un par de comentarios. Por favor revísalos.

2020-04-01 21:14 UTC, jmtov commented on src/components/vistas/foundations-selector/contenedor-fundaciones/styles.module.scss
> +}
Recuerda la línea vacía al final del archivo.

2020-04-01 21:14 UTC, jmtov commented on src/components/vistas/foundations-selector/contenedor-fundaciones/targets/styles.module.scss
> +.containerDates p {
Una clase sería lo más apropiado para este selector.

2020-04-01 21:14 UTC, jmtov commented on src/components/vistas/foundations-selector/contenedor-fundaciones/targets/index.js
> +          <p><b>Direccion:</b></p>
Y después fíjate de aplicarla acá.

2020-04-01 21:14 UTC, jmtov commented on src/components/vistas/foundations-selector/contenedor-fundaciones/targets/index.js
> +      <input type="radio" name="card" id="1" className={styles.radio3} />
¿Por qué `radio3`? Procura usar nombres de clases que reflejen lo que es este componente de la manera más simple.

2020-04-01 21:14 UTC, jmtov commented on src/components/vistas/foundations-selector/contenedor-fundaciones/targets/styles.module.scss
> +  border: solid rgba(128, 128, 128, 0.089) 2px;
Procura usar variables para identificar los colores que se usan en la aplicación y así estandarizar los estilos en un solo lugar.

2020-04-02 00:16 UTC, leoromero97 commented on src/components/vistas/foundations-selector/contenedor-fundaciones/styles.module.scss
> +}
listo !

2020-04-02 00:17 UTC, leoromero97 commented on src/components/vistas/foundations-selector/contenedor-fundaciones/targets/styles.module.scss
> +.containerDates p {
me olvide de borrar la p !

2020-04-02 00:26 UTC, leoromero97 commented on src/components/vistas/foundations-selector/contenedor-fundaciones/targets/index.js
> +          <p><b>Direccion:</b></p>
estaban siendo aplicadas a todas las pe por la clase 'containerDates', ya esta cambiado igual

2020-04-02 00:33 UTC, leoromero97 commented on src/components/vistas/foundations-selector/contenedor-fundaciones/targets/index.js
> +      <input type="radio" name="card" id="1" className={styles.radio3} />
Listo !

2020-04-02 00:33 UTC, leoromero97 commented on src/components/vistas/foundations-selector/contenedor-fundaciones/targets/styles.module.scss
> +  border: solid rgba(128, 128, 128, 0.089) 2px;
listoo

2020-04-02 13:57 UTC, jmtov requested changes
Me parece que los estilos de las tarjetas podrían mejorarse basándose en el diseño que se propuso:

<img width="812" alt="Screen Shot 2020-04-02 at 10 55 44 AM" src="https://user-images.githubusercontent.com/3473831/78257691-92045b00-74d0-11ea-8e04-32f411a81cb3.png">

Recuerda que un diseño normalmente es lo que se le muestra a lxs clientes para poder empezar a desarrollar. Así que lo que lxs clientes esperarían ver lo que el diseño les anticipó.

2020-04-02 13:57 UTC, jmtov commented on src/components/vistas/foundations-selector/contenedor-fundaciones/targets/index.js
> +function Targets() {
Tarjeta en inglés es `Card`.

2020-04-02 13:57 UTC, jmtov commented on src/components/vistas/foundations-selector/contenedor-fundaciones/targets/index.js
> +      <div className={styles.containgerFondo}>
```suggestion
      <div className={styles.containerFondo}>

```

2020-04-02 13:57 UTC, jmtov commented on src/components/vistas/foundations-selector/contenedor-fundaciones/targets/index.js
> +        <div className={styles.containterTitle}>
```suggestion
        <div className={styles.containerTitle}>

```

2020-04-02 13:57 UTC, jmtov commented on src/components/vistas/medicine-selector/index.js
> +        {Tablet}
```suggestion
        <Tablet />
```

2020-04-02 13:57 UTC, jmtov commented on src/components/vistas/tablet/index.js
> +            {FoundationsSelector}
```suggestion
            <FoundationsSelector />
```

2020-04-02 16:29 UTC, leoromero97 commented on src/components/vistas/foundations-selector/contenedor-fundaciones/targets/index.js
> +function Targets() {
Listo !

2020-04-02 16:32 UTC, leoromero97 commented on src/components/vistas/foundations-selector/contenedor-fundaciones/targets/index.js
> +      <div className={styles.containgerFondo}>
Se me paso jeje

2020-04-02 16:37 UTC, leoromero97 commented on src/components/vistas/foundations-selector/contenedor-fundaciones/targets/index.js
> +        <div className={styles.containterTitle}>
Listo

2020-04-02 18:01 UTC, leoromero97 commented on src/components/vistas/medicine-selector/index.js
> +        {Tablet}
Al estar ruteando, no me deja ponerlo como componente de esta forma: <Tablet />

2020-04-02 18:03 UTC, leoromero97 commented on src/components/vistas/tablet/index.js
> +            {FoundationsSelector}
Lo mismo aca !

2020-04-02 19:15 UTC, jmtov approved these changes
Excellent! 💪

2020-04-02 19:15 UTC, jmtov commented on src/components/vistas/foundations-selector/contenedor-fundaciones/index.js
> +          <Cards titleFoundation="HABLEMOS DE HIV" />
¡Bien ahí con el uso de props! 🥇

2020-04-02 19:15 UTC, jmtov commented on src/components/vistas/foundations-selector/contenedor-fundaciones/styles.module.scss
> +  color: #808080ef;
Ten en cuenta lo de los colores en variables globales.

2020-04-02 19:17 UTC, merged