Slide3
jmtov/yosoy-htg pull request #5
Opened 2020-03-25 22:31 UTC by leoromero97

#Descrpcion

Se maqueto la vista del medicamento solucionado, sin funcionalidad. Espero aprobacion.

Adjunto imagenes principales del codigo:

![Captura de pantalla de 2020-03-25 19-30-32](https://user-images.githubusercontent.com/57498210/77591673-36820e00-6ecf-11ea-82b4-4465dce3155a.png)
![Captura de pantalla de 2020-03-25 19-30-36](https://user-images.githubusercontent.com/57498210/77591674-37b33b00-6ecf-11ea-84d4-88f52ddbedae.png)
![Captura de pantalla de 2020-03-25 19-30-51](https://user-images.githubusercontent.com/57498210/77591677-38e46800-6ecf-11ea-9ab1-0ddb8e3ec481.png)

2020-03-30 17:23 UTC, jmtov requested changes
¡Buen trabajo!

Dejé unos comentarios abajo, por favor revísalos.

2020-03-30 17:23 UTC, jmtov commented on src/components/reusable-components/button/index.js
> +export default Button;
Recuerda la línea vacía al final de los archivos.

2020-03-30 17:23 UTC, jmtov commented on package.json
> +    "jscs": "^3.0.7",
¿Para qué están usando esta biblioteca?

2020-03-30 17:23 UTC, jmtov commented on src/components/reusable-components/topbar/back/index.js
> +            <ul className={styles.ul}>
Si esto es sólo un botón, no creo que sea necesario hacer todo el wrapping de `ul` > `li` > `button`. Con sólo el `button` estaría bien.

2020-03-30 17:23 UTC, jmtov commented on src/components/reusable-components/topbar/index.js
> +            <Logo assets={imgNavbar[1]}/>
Como estructuralmente se están separando el botón de back y el botón del logo, no veo que haga falta pasarle las imágenes como prop. Para este caso, recomendaría que la imagen se importe directamente en cada uno de los componentes respectivos. 

Recomendaría este acercamiento si las imágenes que se le pasa a los botones cambiasen bajo ciertos parámetros, pero como en este caso son estáticas, recomendaría no agregar lógica de más a los componentes. 😉

2020-03-30 17:23 UTC, jmtov commented on src/components/reusable-components/topbar/index.js
> +export default Topbar;
Linea vacía al final del archivo.

2020-03-30 17:23 UTC, jmtov commented on src/components/reusable-components/topbar/logo/index.js
> +            <ul className={styles.ul}>
Mismo comentario que en el componente `Back` respecto al wrapping innecesario: `ul` > `li`. Acá recomendaría usar un `div` sencillo o un `button` en caso tal de que al hacer click sobre el logo pasara algo.

2020-03-30 17:23 UTC, jmtov commented on src/components/reusable-components/topbar/logo/styles.module.scss
> +}
Línea vacía al final del archivo.

2020-03-30 17:23 UTC, jmtov commented on src/components/reusable-components/topbar/styles.module.scss
> +.ul {
Ya que en el componente de `topbar` no existen elementos `ul` ni `li`, borraría estas definiciones.

2020-03-30 17:23 UTC, jmtov commented on src/components/vistas/tablet/container-card/card/index.js
> +            <div className={styles.Card}>
Procurar mantener los estilos y el case (mayúsculas/minúsculas) consistente en el nombramiento de las clases.
```suggestion
            <div className={styles.card}>
```

2020-03-30 17:23 UTC, jmtov commented on src/components/vistas/tablet/container-card/card/index.js
> +    ) {
```suggestion
    render() {
```

2020-03-30 17:23 UTC, jmtov commented on src/components/vistas/tablet/container-card/card/qualitybar/index.js
> +class Bar extends React.Component {
Este componente podría ser una función.

2020-03-30 17:23 UTC, jmtov commented on src/components/vistas/tablet/container-card/card/qualitybar/styles.module.scss
> +}
Línea vacía al final del archivo.

2020-03-30 17:23 UTC, jmtov commented on src/components/vistas/tablet/container-card/card/styles.module.scss
> +.Card {
Tener en cuenta el casing (mayúsculas/minúsculas) acá.

2020-03-30 17:23 UTC, jmtov commented on src/components/vistas/tablet/container-card/card/styles.module.scss
> +  flex-wrap: wrap;*/
Cuidado con los espacios de más y los comentarios innecesarios.

2020-03-30 17:23 UTC, jmtov commented on src/components/vistas/tablet/container-card/card/styles.module.scss
> +  box-shadow: 0 10px 10px blue;
Creo que la sombra azul no está en los diseños.

2020-03-30 17:23 UTC, jmtov commented on src/components/vistas/tablet/container-card/card/styles.module.scss
> +.title {
Espacio entre las definiciones.
```suggestion
}

.title {
```

2020-03-30 17:23 UTC, jmtov commented on src/components/vistas/tablet/container-card/index.js
> +            <div className={styles.ContainerCard}>
Mantener el casing consistente.
```suggestion
            <div className={styles.containerCard}>
```

2020-03-30 17:23 UTC, jmtov commented on src/components/vistas/tablet/container-card/styles.module.scss
> +}
Línea vacía al final del archivo.

2020-03-30 17:23 UTC, jmtov commented on src/components/vistas/tablet/container-card/index.js
> +export default ContainerCard;
Línea vacía al final del archivo.

2020-03-30 17:23 UTC, jmtov commented on src/components/vistas/tablet/index.js
> +                    {}
¿Para qué es esta línea?

2020-03-30 17:23 UTC, jmtov commented on src/serviceWorker.js
> +// This optional code is used to register a service worker.
Podrían eliminar este archivo si no lo están usando.

2020-03-30 17:23 UTC, jmtov commented on src/setupTests.js
> +// jest-dom adds custom jest matchers for asserting on DOM nodes.
Este archivo también se podría eliminar.

2020-03-30 19:44 UTC, leoromero97 commented on package.json
> +    "jscs": "^3.0.7",
Me lo recomendaba el Visual Studio Code, crei que es para corregir codigo de jxs

2020-03-31 16:57 UTC, leoromero97 commented on src/components/reusable-components/topbar/back/index.js
> +            <ul className={styles.ul}>
LIsto

2020-03-31 16:58 UTC, leoromero97 commented on src/components/reusable-components/topbar/index.js
> +            <Logo assets={imgNavbar[1]}/>
El boton back, deberia volver atras. Por eso no lo consideramos estatico

2020-03-31 17:05 UTC, leoromero97 commented on src/components/reusable-components/topbar/logo/index.js
> +            <ul className={styles.ul}>
Listo !

2020-03-31 17:05 UTC, leoromero97 commented on src/components/reusable-components/topbar/logo/styles.module.scss
> +}
listo

2020-03-31 17:06 UTC, leoromero97 commented on src/components/reusable-components/topbar/styles.module.scss
> +.ul {
listo

2020-03-31 17:07 UTC, leoromero97 commented on src/components/reusable-components/topbar/index.js
> +export default Topbar;
listo

2020-03-31 17:09 UTC, leoromero97 commented on src/setupTests.js
> +// jest-dom adds custom jest matchers for asserting on DOM nodes.
listo

2020-03-31 17:09 UTC, leoromero97 commented on src/serviceWorker.js
> +// This optional code is used to register a service worker.
listo

2020-03-31 18:01 UTC, leoromero97 commented on src/components/vistas/tablet/container-card/card/index.js
> +            <div className={styles.Card}>
resuelto

2020-03-31 18:02 UTC, leoromero97 commented on src/components/vistas/tablet/container-card/card/index.js
> +    ) {
listo

2020-03-31 18:03 UTC, leoromero97 commented on src/components/vistas/tablet/container-card/card/qualitybar/index.js
> +class Bar extends React.Component {
A futuro el movimiento de la barra iba a ser un evento que le pasaria al componente card

2020-03-31 18:03 UTC, leoromero97 commented on src/components/vistas/tablet/container-card/card/qualitybar/styles.module.scss
> +}
listo

2020-03-31 18:04 UTC, leoromero97 commented on src/components/vistas/tablet/container-card/card/styles.module.scss
> +  flex-wrap: wrap;*/
listo

2020-03-31 18:57 UTC, leoromero97 commented on src/components/vistas/tablet/container-card/card/styles.module.scss
> +  box-shadow: 0 10px 10px blue;
Resuelto !

2020-03-31 18:58 UTC, leoromero97 commented on src/components/vistas/tablet/container-card/card/styles.module.scss
> +.title {
listo

2020-03-31 18:59 UTC, leoromero97 commented on src/components/vistas/tablet/container-card/index.js
> +            <div className={styles.ContainerCard}>
listo

2020-03-31 19:00 UTC, leoromero97 commented on src/components/vistas/tablet/container-card/styles.module.scss
> +}
listo

2020-03-31 19:00 UTC, leoromero97 commented on src/components/vistas/tablet/container-card/index.js
> +export default ContainerCard;
listo

2020-03-31 19:00 UTC, leoromero97 commented on src/components/vistas/tablet/index.js
> +                    {}
Ahi va el siguiente componente

2020-04-01 21:05 UTC, jmtov requested changes
¡Muy buen trabajo con ésta pantalla!

Te dejé un par de comentarios para que revises, por favor.

2020-04-01 21:05 UTC, jmtov commented on src/assets/index.js
> -
¡Bien ahí!

2020-04-01 21:05 UTC, jmtov commented on src/components/reusable-components/topbar/back/index.js
> +class Back extends React.Component {
¿Este componente se necesita? Pensé que se había puesto directamente en el topbar.

2020-04-01 21:05 UTC, jmtov commented on src/components/reusable-components/topbar/logo/index.js
> +class Logo extends React.Component {
Lo mismo para éste componente.

2020-04-01 21:05 UTC, jmtov commented on src/components/vistas/tablet/container-card/card/stick/index.js
> +class Stick extends React.Component {
Sería más apropiado llamar a este componente un slider o algo así, ya que el nombre reflejaría lo que hace en realidad que es deslizarse de un lado a otro.

2020-04-01 21:05 UTC, jmtov commented on src/components/vistas/tablet/container-card/card/stick/styles.module.scss
> +  background: #3f51b5;
Revisa los colores que ya están en variables para que puedan usarlos en toda la aplicación y sean consistentes los estilos.

2020-04-01 21:05 UTC, jmtov commented on src/components/vistas/tablet/container-card/card/stick/styles.module.scss
> +
Se puede borrar éste espacio.

2020-04-01 21:05 UTC, jmtov commented on src/components/vistas/tablet/container-card/card/stick/styles.module.scss
> +  border: 2px solid #3044b1;
Tengan en cuenta el comentario de los colores en variables acá también.

2020-04-01 21:05 UTC, jmtov commented on src/components/vistas/tablet/container-card/card/stick/styles.module.scss
> +    box-shadow: 0 30px 30px #94dbf8;
Y acá.

2020-04-01 21:05 UTC, jmtov commented on src/components/vistas/tablet/container-card/card/styles.module.scss
> +  border: solid rgba(128, 128, 128, 0.089) 4px;
Y acá.

2020-04-01 21:05 UTC, jmtov commented on src/components/vistas/tablet/container-card/card/styles.module.scss
> +  background-color: #d5d2ca;
También acá.

2020-04-01 21:05 UTC, jmtov commented on src/components/vistas/tablet/container-card/card/styles.module.scss
> +  background: #d5d2ca;
Y acá.

2020-04-01 21:05 UTC, jmtov commented on src/components/vistas/tablet/container-card/card/styles.module.scss
> +  -webkit-transform: scale(2);
Usando sólo `transform` (sin el prefijo de navegador) debería funcionar la propiedad. De ser posible, es mejor siempre usar las propiedades estándar para asegurarnos que todo se vea igual en todos los navegadores.

2020-04-01 21:05 UTC, jmtov commented on src/components/vistas/tablet/container-card/index.js
> +}
Atención a la indentación de este archivo. Los demás archivos tienen una indentación de dos espacios por tab. Este tiene 4. Recuerda: **consistencia**.

2020-04-01 21:05 UTC, jmtov commented on src/components/vistas/tablet/styles.module.scss
> +  justify-content: space-evenly;
¡Bien ahí con el uso de estas propiedades!

2020-04-01 21:51 UTC, leoromero97 commented on src/components/reusable-components/topbar/back/index.js
> +class Back extends React.Component {
ya esta eliminado !

2020-04-01 21:51 UTC, leoromero97 commented on src/components/vistas/tablet/container-card/card/stick/index.js
> +class Stick extends React.Component {
listo !

2020-04-01 21:52 UTC, leoromero97 commented on src/components/vistas/tablet/container-card/card/stick/styles.module.scss
> +  background: #3f51b5;
listo !

2020-04-01 21:54 UTC, leoromero97 commented on src/components/vistas/tablet/container-card/card/stick/styles.module.scss
> +
listo !

2020-04-01 21:54 UTC, leoromero97 commented on src/components/vistas/tablet/container-card/card/stick/styles.module.scss
> +  border: 2px solid #3044b1;
listo !

2020-04-01 21:54 UTC, leoromero97 commented on src/components/vistas/tablet/container-card/card/stick/styles.module.scss
> +    box-shadow: 0 30px 30px #94dbf8;
listo !

2020-04-01 21:57 UTC, leoromero97 commented on src/components/vistas/tablet/container-card/card/styles.module.scss
> +  border: solid rgba(128, 128, 128, 0.089) 4px;
listo !

2020-04-01 22:00 UTC, leoromero97 commented on src/components/vistas/tablet/container-card/card/styles.module.scss
> +  background-color: #d5d2ca;
listo !

2020-04-01 22:00 UTC, leoromero97 commented on src/components/vistas/tablet/container-card/card/styles.module.scss
> +  background: #d5d2ca;
listo !

2020-04-01 22:00 UTC, leoromero97 commented on src/components/vistas/tablet/container-card/card/styles.module.scss
> +  -webkit-transform: scale(2);
gracias kike !

2020-04-01 22:01 UTC, leoromero97 commented on src/components/vistas/tablet/container-card/index.js
> +}
Listo !

2020-04-02 13:52 UTC, jmtov approved these changes
¡Muy bien!

2020-04-02 16:19 UTC, merged