Slide6
jmtov/yosoy-htg pull request #6
Opened 2020-03-25 22:37 UTC by leoromero97

#Descripcion

Se termino de maquetar la vista de la camara cuando vas scanear la foto del DNI.

Adjunto imagenes principales de codigo
![Captura de pantalla de 2020-03-25 19-36-44](https://user-images.githubusercontent.com/57498210/77592055-14d55680-6ed0-11ea-9416-584a6925fe15.png)
![Captura de pantalla de 2020-03-25 19-37-28](https://user-images.githubusercontent.com/57498210/77592059-16068380-6ed0-11ea-944b-15fdfe681171.png)

2020-03-30 17:50 UTC, jmtov requested changes

2020-03-30 17:50 UTC, jmtov commented on src/components/assets/index.js
> +const imgNavbar = [
Este cambio está en otro PR, ¿no?

2020-03-30 17:50 UTC, jmtov commented on src/components/camara/index.js
> +            </div>
Prestar atención a los espaciados, indentación y espacios de más (y de menos)
```suggestion
        return (
            <div>
                <div className={styles.cam}>
                    <img src={camara} alt='camara' />
                </div>
            </div>
```

También, ¿es necesario envolver la imagen en dos `div`s?

2020-03-30 17:50 UTC, jmtov commented on src/components/camara/index.js
> +export default Camara;
Línea vacía al final del archivo.

2020-03-30 17:50 UTC, jmtov commented on src/components/camara/styles.module.scss
> +}
Línea vacía al final del archivo.

2020-03-30 17:50 UTC, jmtov commented on src/components/topbar/atras/index.js
> +
Creo que en [este PR](https://github.com/jmtov/yosoy-htg/pull/5) se agregaba un botón de `Back`, ¿no?

2020-03-30 17:50 UTC, jmtov commented on src/components/topbar/logo/index.js
> +
Tener en cuenta los comentarios que se hicieron en [este PR](https://github.com/jmtov/yosoy-htg/pull/5) respecto a los elementos que envuelven a la imagen.

2020-03-30 17:50 UTC, jmtov commented on src/components/topbar/logo/index.js
> +export default Logo;
Línea vacía al final del archivo.

2020-03-30 17:50 UTC, leoromero97 commented on src/components/assets/index.js
> +const imgNavbar = [
sii

2020-03-30 17:51 UTC, leoromero97 commented on src/components/assets/index.js
> +const imgNavbar = [
en el de home, cuando se mergea resolvemos conflictos

2020-04-01 01:30 UTC, leoromero97 commented on src/components/camara/index.js
> +            </div>
Un div encierra la imagen, el otro div encierra la topbar, ya esta corregido !

2020-04-01 01:31 UTC, leoromero97 commented on src/components/camara/index.js
> +export default Camara;
listo

2020-04-01 01:31 UTC, leoromero97 commented on src/components/camara/styles.module.scss
> +}
listo

2020-04-01 01:33 UTC, leoromero97 commented on src/components/topbar/atras/index.js
> +
si, igual ya esta corregido, solo tiene la etiqueta button !

2020-04-01 01:33 UTC, leoromero97 commented on src/components/topbar/logo/index.js
> +
listo !

2020-04-01 01:34 UTC, leoromero97 commented on src/components/topbar/logo/index.js
> +export default Logo;
listo !

2020-04-01 21:26 UTC, jmtov approved these changes
¡Muy bien!

Por favor no hagas merge de esto hasta que no se haya hecho merge con la rama `slide5`.

2020-04-03 15:04 UTC, merged