Slide5
jmtov/yosoy-htg pull request #7
Opened 2020-03-26 16:21 UTC by rilmarramos

2020-03-30 19:43 UTC, jmtov requested changes

2020-03-30 19:43 UTC, jmtov commented on src/components/reusable-components/searcher/form/index.js
> +                <input type="text" placeholder={this.props.contBuscador} className={styles.buscador2}/>
Te recomiendo llamar esta clase `buscador` y al contenedor usar la clase `contenedorBuscador`, con eso es más fácil identificarlos.

2020-03-30 19:43 UTC, jmtov commented on src/components/reusable-components/searcher/form/index.js
> +                    <img src="./back.png" className={styles.lupa} alt=""/>
Te recomiendo abstraer un poco el nombre de las clases para que no se hable propiamente de lo que se ve si no de lo que representa, así será más fácil para quien use el código después, entender de qué se habla:
```suggestion
                <div className={styles.contenedorIcono}>
                    <img src="./back.png" className={styles.icono} alt=""/>
```

2020-03-30 19:43 UTC, jmtov commented on src/components/reusable-components/searcher/form/index.js
> +
No dejes espacios de más.

2020-03-30 19:43 UTC, jmtov commented on src/components/reusable-components/searcher/form/index.js
> +export default Form;
Recuerda la línea vacía al final del archivo. Puedes encontrar más información acerca de esto en el [documento](https://docs.google.com/document/d/1gJ0gB1NkinQXyRe5dk71yMUYE8c6dupLc-lYQ0osSro) para estandarizar el código.

2020-03-30 19:43 UTC, jmtov commented on src/components/reusable-components/searcher/form/styles.module.scss
> +}
Recuerda la línea vacía al final de los archivos.

2020-03-30 19:43 UTC, jmtov commented on src/components/reusable-components/searcher/form/styles.module.scss
> +.buscador{
Ten presente los espaciados en el código: 
```suggestion
.buscador {
```

2020-03-30 19:43 UTC, jmtov commented on src/components/reusable-components/searcher/form/styles.module.scss
> +.lupa1{
También acá.

2020-03-30 19:43 UTC, jmtov commented on src/components/reusable-components/searcher/form/styles.module.scss
> +.lupa{
Acá.

2020-03-30 19:43 UTC, jmtov commented on src/components/reusable-components/searcher/form/styles.module.scss
> +.buscador2{
Y acá.

2020-03-30 19:43 UTC, jmtov commented on src/components/reusable-components/searcher/form/index.js
> +                <input type="text" placeholder={this.props.contBuscador} className={styles.buscador2}/>
También, no veo necesario que el `placeholder` de este input venga como `props` ya que no se está modificando en ningún momento. Podrías ponerlo como texto estático.

2020-03-30 19:43 UTC, jmtov commented on src/components/reusable-components/searcher/styles.module.scss
> +}
Recuerda la línea vacía al final del archivo.

2020-03-30 19:43 UTC, jmtov commented on src/components/reusable-components/topbar/back/index.js
> +class Back extends React.Component {
Creo que este componente se desarrolló en [otros PRs](https://github.com/jmtov/yosoy-htg/pull/5). Por favor revísalos para que no haya conflictos.

2020-03-30 19:43 UTC, jmtov commented on src/components/reusable-components/topbar/index.js
> +function Topbar() {
La `topbar` también se estaba trabajando en [otros PRs](https://github.com/jmtov/yosoy-htg/pull/5).

2020-03-30 19:43 UTC, jmtov commented on src/components/vistas/scaner/index.js
> +        <div className={styles.Scaner}>
Ten cuidado con que los nombres de las clases sean consistentes en el casing (mayúsculas/minúsculas).
```suggestion
        <div className={styles.scaner}>
```

2020-03-30 19:43 UTC, jmtov commented on src/components/vistas/scaner/index.js
> +                    <strong>
Acá podrías usar un `p` en vez de un `strong`. Usa `strong` solamente para dar énfasis a una palabra o una pequeña frase dentro de un párrafo. Te dejo un [artículo](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strong) con más información al respecto.

2020-03-30 19:43 UTC, jmtov commented on src/components/vistas/scaner/index.js
> +            esté reservado solo para vos{" "}
¿Para qué es este `{" "}`?

2020-03-30 19:43 UTC, jmtov commented on src/components/vistas/scaner/index.js
> +                        {}
Creo que esta línea es innecesaria.

2020-03-30 19:43 UTC, jmtov commented on src/components/vistas/scaner/styles.module.scss
> +  color: rgb(68, 118, 255);
Como este color se repite en varios lugares, podrías usar variables de SCSS para no tener que escribir varias veces el mismo color.

2020-03-30 19:43 UTC, jmtov commented on src/components/vistas/scaner/index.js
> +                <div className={styles.containerScaner}>
No hace falta usar dos `div`s para contener éstos elementos.

2020-03-30 19:43 UTC, jmtov commented on src/components/vistas/scaner/index.js
> +                <div className={styles.containercamera}>
Acá tampoco.

2020-03-30 19:43 UTC, jmtov commented on src/components/vistas/scaner/styles.module.scss
> +  width: 14%;
Intenta no usar valores tan arbitrarios para los anchos de los elementos. ¿Qué pasaría si este componente se viese desde una pantalla chica? Probablemente tendrá un espacio muy pequeño para mostrarse y se vería raro.

2020-03-30 19:43 UTC, jmtov commented on src/components/vistas/scaner/styles.module.scss
> +  width: 16%;
Lo mismo acá.

2020-03-30 19:43 UTC, jmtov commented on src/components/vistas/scaner/styles.module.scss
> +  left: 38%;
Y también para las márgenes.

2020-03-30 19:43 UTC, jmtov commented on src/index.js
> +    </BrowserRouter>, rootElement
Esto se estaba haciendo en [otro PR](https://github.com/jmtov/htg-javascript/pull/5) también.

2020-03-31 05:45 UTC, leoromero97 commented on src/components/reusable-components/searcher/form/index.js
> +                <input type="text" placeholder={this.props.contBuscador} className={styles.buscador2}/>
Kike, esta resuelto lo primero sobre la confusion de estilos.
Respecto al placeholder le pasamos props porque despues lo volvemos a utilizar y para no crear otro componente, solo le cambiamos las props

2020-03-31 05:46 UTC, leoromero97 commented on src/components/reusable-components/searcher/form/index.js
> +
resuelto

2020-03-31 05:47 UTC, leoromero97 commented on src/components/reusable-components/searcher/form/index.js
> +export default Form;
listo

2020-03-31 05:47 UTC, leoromero97 commented on src/components/reusable-components/searcher/form/styles.module.scss
> +}
listo

2020-03-31 05:48 UTC, leoromero97 commented on src/index.js
> +    </BrowserRouter>, rootElement
asi es

2020-03-31 06:37 UTC, leoromero97 commented on src/components/vistas/scaner/styles.module.scss
> +  width: 14%;
resuelto

2020-03-31 06:38 UTC, leoromero97 commented on src/components/vistas/scaner/styles.module.scss
> +  left: 38%;
listoo

2020-04-01 21:20 UTC, jmtov requested changes
¡Buen trabajo Rilmar! 

Te dejé unos comentarios abajo.

2020-04-01 21:20 UTC, jmtov commented on src/app.js
> +>>>>>>> 3cb7f78181eab1ceee199514d54b1b013afc3c71
¡Cuidado con hacer el merge de estas cosas cuando se solucionan conflictos! Esto estalla la aplicación.

2020-04-01 21:20 UTC, jmtov commented on src/components/vistas/scaner/index.js
> +          <h1 className={styles.titleScan}>Escanear acá</h1> <br /> <br />
No hace falta usar `<br />`s acá.
```suggestion
          <h1 className={styles.titleScan}>Escanear acá</h1>
```

2020-04-01 21:20 UTC, jmtov commented on src/components/vistas/scaner/index.js
> +
Cuidado con los espacios de más.

2020-04-01 21:20 UTC, jmtov commented on src/components/vistas/scaner/index.js
> +          </strong>
Normalmente las etiquetas `strong` se usan para resaltar ideas importantes dentro de un párrafo. Para este caso, recomendaría que usaras una etiqueta `p` normal.

2020-04-01 21:20 UTC, jmtov commented on src/components/vistas/scaner/styles.module.scss
> +  color: rgb(68, 118, 255);
Ten en cuenta el comentario de las variables de color acá también.

2020-04-01 21:20 UTC, jmtov commented on src/components/vistas/scaner/styles.module.scss
> +  color: rgb(68, 118, 255);
Y acá también. (Respecto al comentario de variables de color)

2020-04-01 21:20 UTC, jmtov commented on src/components/vistas/scaner/index.js
> +function Scaner() {
En inglés, `Scanner` es con doble N.

2020-04-02 00:47 UTC, leoromero97 commented on src/components/vistas/scaner/index.js
> +function Scaner() {
listo graciass !

2020-04-02 00:51 UTC, leoromero97 commented on src/app.js
> +>>>>>>> 3cb7f78181eab1ceee199514d54b1b013afc3c71
listo

2020-04-02 00:57 UTC, leoromero97 commented on src/components/vistas/scaner/index.js
> +          <h1 className={styles.titleScan}>Escanear acá</h1> <br /> <br />
okkk

2020-04-02 00:57 UTC, leoromero97 commented on src/components/vistas/scaner/index.js
> +
listo

2020-04-02 00:58 UTC, leoromero97 commented on src/components/vistas/scaner/index.js
> +          </strong>
gracias por el dato !

2020-04-02 01:01 UTC, leoromero97 commented on src/components/vistas/scaner/styles.module.scss
> +  color: rgb(68, 118, 255);
listoo

2020-04-02 01:01 UTC, leoromero97 commented on src/components/vistas/scaner/styles.module.scss
> +  color: rgb(68, 118, 255);
listoo

2020-04-02 14:42 UTC, jmtov requested changes
¡Muy bien! Te dejé algunos comentarios.

2020-04-02 14:42 UTC, jmtov commented on src/components/medicine-container/styles.module.scss
> +$color-title:#808080ef;
Si esta variable se repite, se podría poner en un archivo de estilos más global para que toda la app sepa que existe este color y no se tenga que crear en todos los archivos donde se quiera usar.

2020-04-02 14:42 UTC, jmtov commented on src/components/vistas/foundations-selector/contenedor-fundaciones/styles.module.scss
> +$color-title:#808080ef;
Tener en cuenta el comentario respecto a las variables.

2020-04-02 14:42 UTC, jmtov commented on src/components/vistas/foundations-selector/index.js
> +          {Scanner}
Preferir notación en JSX.
```suggestion
          <Scanner />
```

2020-04-02 14:42 UTC, jmtov commented on src/components/vistas/scanner/styles.module.scss
> +
Atento a los espacios de más.

2020-04-02 14:42 UTC, jmtov commented on src/components/vistas/scanner/styles.module.scss
> +$border-target: #80808017;
Si usas estos colores en otro lugar de la aplicación, puedes centralizar esos colores en un solo archivo

2020-04-02 18:48 UTC, leoromero97 commented on src/components/vistas/foundations-selector/contenedor-fundaciones/styles.module.scss
> +$color-title:#808080ef;
Ok, en los 3 casos poner las variables en el main !

2020-04-02 18:48 UTC, leoromero97 commented on src/components/vistas/foundations-selector/index.js
> +          {Scanner}
No puedo rutear si escribo notacion JSX

2020-04-03 14:51 UTC, jmtov approved these changes

2020-04-03 14:51 UTC, jmtov commented on src/components/vistas/foundations-selector/contenedor-fundaciones/cards/styles.module.scss
> +
Ojo con los espacios de más.

2020-04-03 14:51 UTC, jmtov commented on src/components/vistas/foundations-selector/contenedor-fundaciones/index.js
> +          <Cards titleFoundation="FUNDACIÓN ROSAS"/>
💪

2020-04-03 14:51 UTC, jmtov commented on src/components/vistas/scanner/index.js
> +          </p>
Cuidado con la indentación.

2020-04-03 14:54 UTC, leoromero97 commented on src/components/vistas/foundations-selector/contenedor-fundaciones/cards/styles.module.scss
> +
listo

2020-04-03 14:55 UTC, leoromero97 commented on src/components/vistas/scanner/index.js
> +          </p>
listo

2020-04-03 14:56 UTC, merged