cree vista 7
jmtov/yosoy-htg pull request #8
Opened 2020-03-26 16:27 UTC by rilmarramos

#Descripcion

Maquetado de slide 7

2020-04-01 21:31 UTC, jmtov requested changes
Excellent!

Te dejo unos comentarios.

2020-04-01 21:31 UTC, jmtov commented on src/components/reusable-components/button/index.js
> +    );
¡Muy bien con esa atención a los detalles!

2020-04-01 21:31 UTC, jmtov commented on src/components/vistas/confirmation/index.js
> +          <br></br> Recordá que solo podemos reservar la medicación que pediste durante las proximas 72hs.</p>
No es necesario tener tantos `<br />`s. Si se necesita separar el contenido entre párrafos, podrían optar por estilos en CSS.

2020-04-01 21:31 UTC, jmtov commented on src/components/vistas/confirmation/styles.module.scss
> +@import url('https://fonts.googleapis.com/css2?family=Roboto:wght@900&display=swap');
Haría este `import` en un lugar más global de la aplicación como en `src/styles/main.scss` con eso no tienen que importar la fuente en cada archivo y así podrían normalizar la apariencia de la aplicación.

2020-04-01 21:31 UTC, jmtov commented on src/components/vistas/confirmation/styles.module.scss
> +  background-color: rgba(33, 90, 211, 0.651);
Recuerda usar variables para los colores de la aplicación.

2020-04-01 21:31 UTC, jmtov commented on src/components/vistas/confirmation/styles.module.scss
> +  color: white;
Igual acá.

2020-04-01 21:31 UTC, jmtov commented on src/components/vistas/confirmation/styles.module.scss
> +  color: rgba(1, 26, 80, 0.527);
También acá.

2020-04-01 21:31 UTC, jmtov commented on src/components/vistas/confirmation/styles.module.scss
> +  color: rgba(1, 26, 80, 0.555);
Y acá.

2020-04-01 21:31 UTC, jmtov commented on src/components/vistas/confirmation/styles.module.scss
> +  color: rgba(33, 90, 211, 0.651);
Y en estos dos.

2020-04-02 06:32 UTC, leoromero97 commented on src/components/vistas/confirmation/styles.module.scss
> +  background-color: rgba(33, 90, 211, 0.651);
listo !

2020-04-02 06:34 UTC, leoromero97 commented on src/components/vistas/confirmation/styles.module.scss
> +  color: white;
LIsto !

2020-04-02 06:34 UTC, leoromero97 commented on src/components/vistas/confirmation/styles.module.scss
> +  color: rgba(1, 26, 80, 0.527);
listo !

2020-04-02 06:35 UTC, leoromero97 commented on src/components/vistas/confirmation/styles.module.scss
> +  color: rgba(1, 26, 80, 0.555);
listo

2020-04-02 06:35 UTC, leoromero97 commented on src/components/vistas/confirmation/styles.module.scss
> +  color: rgba(33, 90, 211, 0.651);
listo

2020-04-02 06:54 UTC, leoromero97 commented on src/components/vistas/confirmation/styles.module.scss
> +  color: rgba(33, 90, 211, 0.651);
listo

2020-04-02 06:54 UTC, leoromero97 commented on src/components/vistas/confirmation/styles.module.scss
> +  color: rgba(1, 26, 80, 0.555);
listo

2020-04-02 06:54 UTC, leoromero97 commented on src/components/vistas/confirmation/styles.module.scss
> +  color: rgba(1, 26, 80, 0.527);
listo

2020-04-02 06:54 UTC, leoromero97 commented on src/components/vistas/confirmation/styles.module.scss
> +  color: white;
listo

2020-04-02 06:55 UTC, leoromero97 commented on src/components/vistas/confirmation/styles.module.scss
> +  background-color: rgba(33, 90, 211, 0.651);
listo

2020-04-02 06:56 UTC, leoromero97 commented on src/components/vistas/confirmation/styles.module.scss
> +@import url('https://fonts.googleapis.com/css2?family=Roboto:wght@900&display=swap');
Creo que en la app hay 3 fuentes, esta puesta en este slide para probar

2020-04-02 06:56 UTC, leoromero97 commented on src/components/vistas/confirmation/index.js
> +          <br></br> Recordá que solo podemos reservar la medicación que pediste durante las proximas 72hs.</p>
Listoo

2020-04-02 14:51 UTC, jmtov requested changes
Hay muchos archivos que me parece que vienen de otros PRs. Por favor revisa las bases y asegúrate de que esta rama y su base estén actualizadas con los últimos cambios que han sido solicitados.

2020-04-02 14:51 UTC, jmtov commented on src/components/vistas/confirmation/index.js
> +        <p >La Fundacion Hablemos de HIV te está esperando.</p>
Atento a los espacios de más. También, ¿no debería tener este elemento la clase `text`?
```suggestion
        <p>La Fundacion Hablemos de HIV te está esperando.</p>
```

2020-04-02 14:51 UTC, jmtov commented on src/components/vistas/confirmation/styles.module.scss
> +@import url('https://fonts.googleapis.com/css2?family=Roboto:wght@900&display=swap');
Si estaba para probar, los cambios de cosas para probar no deberían estar en el PR puesto que una vez unido a development podría ser probado por el equipo de testing (de haberlo) y luego sería subido a producción. Es importante no dejar código de pruebas en los PRs por que es código que si bien sirve para pruebas mientras uno trabaja, quizá no le importe a quien viene después y puede generar confusiones.

2020-04-02 19:27 UTC, leoromero97 commented on src/components/vistas/confirmation/index.js
> +        <p >La Fundacion Hablemos de HIV te está esperando.</p>
se me paso, listo !

2020-04-03 14:54 UTC, jmtov approved these changes

2020-04-03 14:54 UTC, jmtov commented on src/components/vistas/camara/index.js
> +            {Confirmation}
```suggestion
            <Confirmation />
```

2020-04-03 15:14 UTC, leoromero97 commented on src/components/vistas/camara/index.js
> +            {Confirmation}
Okkk

2020-04-03 15:14 UTC, merged