se termino la vista home mobile
jmtov/yosoy-htg pull request #9
Opened 2020-04-08 21:14 UTC by leoromero97

Mobile home

2020-04-09 13:47 UTC, briangerez requested changes

2020-04-09 13:47 UTC, briangerez commented on src/components/reusable-components/searcher/styles.module.scss
> +    width: 74%;
Dos cositas:
- Ojo con la identación. Si es de 2 espacios, debería mantenerla en el resto del proyecto!

- Estos porcentajes, no afectan a la pantalla de Escritorio? Me gustaría ver una screenshot de la versión de escritorio para comprobar esto.

2020-04-09 13:47 UTC, briangerez commented on src/components/screens/desktop/home/styles.module.scss
> +@import url('https://fonts.googleapis.com/css2?family=Open+Sans:wght@700&display=swap');
Recomendación: 
Puede agregar este import dentro del archivo principal de sass, para que sea global a todo el proyecto y no tengas que importarlo en cada archivo de estilos que uses. Por lo que veo en su proyecto es en `src/styles/main.scss`

Para los colores lo mismo. Así queda todo centralizado y cuando necesites usarlos, importarlos como: 
@import '../../styles/main.scss';
 También puede poner nombres más descriptivos a los colores, una idea puede ser poner el nombre del color. Por ejemplo, cambiar el nombre hr-color por brightGray

2020-04-09 13:47 UTC, briangerez commented on src/components/screens/desktop/medicine-selector/medicine-container/styles.module.scss
>  $color-title:#808080ef;
Este también lo puede mover al archivo donde están los colores 😄

2020-04-09 16:36 UTC, leoromero97 commented on src/components/reusable-components/searcher/styles.module.scss
> +    width: 74%;
Sobre la identacion, perdon se me paso. el porcentaje es en otra vista, pero en el proximo merge vas a ver que no afecta a la pantalla de escritorio

2020-04-09 18:26 UTC, leoromero97 commented on src/components/screens/desktop/medicine-selector/medicine-container/styles.module.scss
>  $color-title:#808080ef;
listo

2020-04-09 18:26 UTC, leoromero97 commented on src/components/screens/desktop/home/styles.module.scss
> +@import url('https://fonts.googleapis.com/css2?family=Open+Sans:wght@700&display=swap');
resuelto !

2020-04-13 13:57 UTC, briangerez requested changes
Genial Leo! Ya casi lo tenes. Te dejo unos detalles! 💪

2020-04-13 13:57 UTC, briangerez commented on src/components/reusable-components/searcher/styles.module.scss
> +@import url('https://fonts.googleapis.com/css2?family=Lato:ital@0;1&display=swap');
Este seguro que no hace falta ponerlo aquí, si ya está definido en el mail.scss

2020-04-13 13:57 UTC, briangerez commented on src/components/reusable-components/searcher/index.js
> +     <form action="" className={styles.containerSearcher}>
Ese action creo que está de más 👀

2020-04-13 13:57 UTC, briangerez commented on src/components/reusable-components/searcher/index.js
>  class Searcher extends React.Component {
Cuando el componente no utiliza los estados internos ni los métodos del ciclo de vida, es mejor utilizar una function directamente. 😄

2020-04-13 13:57 UTC, briangerez commented on src/components/reusable-components/topbar/styles.module.scss
> +.nav {
Ojo acá, con la identación 😃

2020-04-13 13:57 UTC, briangerez commented on src/components/screens/desktop/camara/index.js
> +              <img src={back} className={styles.iconBack} alt="back" />
Deberías mantener el mismo idioma para los alts! Acordate que tienen que ser lo más descriptivos posible, cuando se trata de una imagen no decorativa.

2020-04-13 13:57 UTC, briangerez commented on src/components/screens/desktop/camara/index.js
> +            <img src={logo} className={styles.iconLogo} alt="logo" />
Logo de qué?

2020-04-13 13:57 UTC, briangerez commented on src/components/screens/desktop/confirmation/index.js
> +
Este espacio es innecesario

2020-04-13 13:57 UTC, briangerez commented on src/components/screens/desktop/confirmation/index.js
> +
Igual que este

2020-04-13 13:57 UTC, briangerez commented on src/components/screens/desktop/medicine-selector/medicine-container/styles.module.scss
>  $color-title:#808080ef;
Este color lo podes sacar de aquí si están todos definidos en el main!

2020-04-13 14:01 UTC, leoromero97 commented on src/components/reusable-components/searcher/styles.module.scss
> +@import url('https://fonts.googleapis.com/css2?family=Lato:ital@0;1&display=swap');
Lo puse ahi porque esa fuente se utiliza en ese componente, pero ya lo paso a main, gracias !

2020-04-13 14:01 UTC, leoromero97 commented on src/components/reusable-components/searcher/index.js
>  class Searcher extends React.Component {
Lo tomo, pero este componente va a funcionar..

2020-04-13 14:02 UTC, leoromero97 commented on src/components/reusable-components/topbar/styles.module.scss
> +.nav {
listo

2020-04-13 14:03 UTC, leoromero97 commented on src/components/screens/desktop/camara/index.js
> +            <img src={logo} className={styles.iconLogo} alt="logo" />
Es el logo general de la app, esta en la topbar, y es el unico logo por el momento

2020-04-13 14:04 UTC, leoromero97 commented on src/components/screens/desktop/confirmation/index.js
> +
listo

2020-04-13 14:04 UTC, leoromero97 commented on src/components/screens/desktop/confirmation/index.js
> +
listo

2020-04-13 14:06 UTC, leoromero97 commented on src/components/screens/desktop/medicine-selector/medicine-container/styles.module.scss
>  $color-title:#808080ef;
listo

2020-04-13 14:26 UTC, briangerez commented on src/components/screens/desktop/tablet/container-card/card/styles.module.scss
> +/*
Se te escapó este comentario?
Si no vas a usar este código, deberías borrarlo!

2020-04-13 18:37 UTC, luisrodolfoduarte commented on src/components/reusable-components/searcher/index.js
> +     <form action="" className={styles.containerSearcher}>
listo

2020-04-13 18:39 UTC, luisrodolfoduarte commented on src/components/screens/desktop/camara/index.js
> +              <img src={back} className={styles.iconBack} alt="back" />
listo

2020-04-13 18:40 UTC, luisrodolfoduarte commented on src/components/screens/desktop/tablet/container-card/card/styles.module.scss
> +/*
listo

2020-04-13 19:05 UTC, briangerez approved these changes
Excelente laburo! Te comenté unos muy pequeños detalles para que te quede más prolijo! 

Otro detalle, cuando solucionas alguna corrección, los commits agregados deben ser **sólo** de esos cambios y **no** cosas nuevas porque sino es más dificil hacer seguimiento de las correcciones ya que se agregan cosas nuevas que no había visto antes.

Más allá de eso, genial! 🎉

2020-04-13 19:05 UTC, briangerez commented on src/components/screens/camara/index.js
>              {Confirmation}
Esto lo podes remover para los siguientes PRs!

2020-04-13 19:05 UTC, briangerez commented on src/components/screens/medicine-selector/index.js
> +        {Tablet}
Esto también!

2020-04-13 19:05 UTC, briangerez commented on src/components/screens/tablet/index.js
>              {FoundationsSelector}
y estee

2020-04-13 20:56 UTC, luisrodolfoduarte commented on src/components/screens/camara/index.js
>              {Confirmation}
los componentes, ok !

2020-04-13 20:57 UTC, merged